;; A non-square (rectangular) rank-2 box-sum-from-origin: nx != ny
(define (main)
  (let ((nx 30)
        (ny 50)
        (v (make-vector 1500 0))
        (s (make-vector 1500 0)))
    (do ((p 0 (+ p 1))) ((= p 1500))
      (vector-set! v p (+ 1 (remainder (* p 17) 9))))
    (do ((i 0 (+ i 1))) ((= i nx))
      (do ((j 0 (+ j 1))) ((= j ny))
        (let ((acc 0))
          (do ((a 0 (+ a 1))) ((= a (+ i 1)))
            (do ((b 0 (+ b 1))) ((= b (+ j 1)))
              (set! acc (+ acc (vector-ref v (+ (* a ny) b))))))
          (vector-set! s (+ (* i ny) j) acc))))
    (display (vector-ref s (+ (* 29 ny) 49)))
    (newline)
    0))
