(define (main)
  (let ((n 200)
        (v (make-vector 40000 1))
        (s (make-vector 40000 0)))
    (do ((i 0 (+ i 1)))
        ((= i n))
      (do ((j 0 (+ j 1)))
          ((= j n))
        (let ((acc (vector-ref v (+ (* i n) j))))
          (if (< 0 i)
              (set! acc (+ acc (vector-ref s (+ (* (- i 1) n) j))))
              0)
          (if (< 0 j)
              (set! acc (+ acc (vector-ref s (+ (* i n) (- j 1)))))
              0)
          (if (< 0 (* i j))
              (set! acc (- acc (vector-ref s (+ (* (- i 1) n) (- j 1)))))
              0)
          (vector-set! s (+ (* i n) j) acc))))
    (display (vector-ref s 39999))
    (newline)
    0))
