;; A rank-3 box-sum-from-origin: s[i][j][k] = sum over [0,i]x[0,j]x[0,k]
(define (main)
  (let ((n 10)
        (v (make-vector 1000 0))
        (s (make-vector 1000 0)))
    (do ((p 0 (+ p 1))) ((= p 1000))
      (vector-set! v p (+ 1 (remainder (* p 13) 5))))
    (do ((i 0 (+ i 1))) ((= i n))
      (do ((j 0 (+ j 1))) ((= j n))
        (do ((k 0 (+ k 1))) ((= k n))
          (let ((acc 0))
            (do ((a 0 (+ a 1))) ((= a (+ i 1)))
              (do ((b 0 (+ b 1))) ((= b (+ j 1)))
                (do ((c 0 (+ c 1))) ((= c (+ k 1)))
                  (set! acc (+ acc (vector-ref v (+ (* (+ (* a n) b) n) c)))))))
            (vector-set! s (+ (* (+ (* i n) j) n) k) acc)))))
    (display (vector-ref s (+ (* (+ (* 9 n) 9) n) 9)))
    (newline)
    0))
