(define (main)
  (let ((n 200)
        (v (make-vector 40000 1))
        (s (make-vector 40000 0)))
    (do ((i 0 (+ i 1)))
        ((= i n))
      (do ((j 0 (+ j 1)))
          ((= j n))
        (let ((acc 0))
          (do ((a 0 (+ a 1)))
              ((= a (+ i 1)))
            (do ((b 0 (+ b 1)))
                ((= b (+ j 1)))
              (set! acc (+ acc (vector-ref v (+ (* a n) b))))))
          (vector-set! s (+ (* i n) j) acc))))
    (display (vector-ref s 39999))
    (newline)
    0))
