(define (main)
  (let ((n 10)
        (i 1)
        (m 0))
    (let loop ()
      (if (< i n)
          (begin (set! m (+ m 1))
                 (set! i (+ i i))
                 (loop))))
    (display m)
    (newline)
    (display (let pow ((k 5) (p 1)) (if (zero? k) p (pow (- k 1) (* 2 p)))))
    (newline)
    0))
