(define (main)
  (let ((n 20000)
        (v (make-vector 20000 1))
        (s (make-vector 20000 0)))
    (do ((i 0 (+ i 1)))
        ((= i n))
      (let ((acc 0))
        (do ((j 0 (+ j 1)))
            ((= j (+ i 1)))
          (set! acc (+ acc (vector-ref v j))))
        (vector-set! s i acc)))
    (display (vector-ref s (- n 1)))
    (newline)
    0))
